version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running Django tests"
      - python manage.py test

  build:
    commands:
      - echo "Building the application"
      - python manage.py collectstatic --noinput
      - python manage.py migrate --noinput

  post_build:
    commands:
      - echo "Running post-build"
       

artifacts:
  files:
    - "**/*" 
  discard-paths: no

cache:
  paths:
    - "/root/.cache/pip"  
